language: python
python:
  - "2.7"
script: ./runtests.sh
env:
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.9.4
  - DJANGO_VERSION=1.10.3

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - python setup.py -q install
